# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/cache-external-data'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/downstream-build'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/key4hep-build'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/workflows'
    schedule:
      interval: 'weekly'
