name: Key4hep build
description: Build and test using the Key4hep stack

runs:
  using: "composite"
  steps:
    - name: Start container
      shell: bash
      run: |
        docker run -it --name CI_container --device /dev/fuse -v ${GITHUB_WORKSPACE}:/Package/main -d ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest /bin/bash

    - name: Setup environment and build
      run: |
          /mount.sh
          cd /Package
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../install -G Ninja
          ninja install
          ctest -j $(nproc) --output-on-failure

