name: Key4hep build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep-images/alma9-build:latest

    strategy:
        fail-fast: false
        matrix:
        release: ["sw.hsf.org/key4hep",
                    "sw-nightlies.hsf.org/key4hep"]

    <<: *build_strategy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v3

      - name: Setup environment and build
        run: |
            source ${{ matrix.release }}/setup.sh
            mkdir build
            cd build
            cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../install -G Ninja
            ninja install
            ctest -j $(nproc) --output-on-failure

  job2:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep-images/ubuntu22-build:latest

    <<: *build_strategy

    strategy:
        fail-fast: false
        matrix:
        release: ["sw.hsf.org/key4hep",
                    "sw-nightlies.hsf.org/key4hep"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v3

      - name: Setup environment and build
        run: |
            source ${{ matrix.release }}/setup.sh
            mkdir build
            cd build
            cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../install -G Ninja
            ninja install
            ctest -j $(nproc) --output-on-failure


  job3:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep-images/centos7-build:latest

    <<: *build_strategy

    strategy:
        fail-fast: false
        matrix:
        release: ["sw.hsf.org/key4hep",
                    "sw-nightlies.hsf.org/key4hep"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v3

      - name: Setup environment and build
        run: |
            source ${{ matrix.release }}/setup.sh
            mkdir build
            cd build
            cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../install -G Ninja
            ninja install
            ctest -j $(nproc) --output-on-failure

