name: Key4hep build
description: Build and test using the Key4hep stack

inputs:
  build_type:
    description: "release" or "nightly"
    required: true
  image:
    description: "alma9", "ubuntu22" or "centos7"
    required: true

runs:
  using: "composite"
  steps:
    - name: Start container
      shell: bash
      run: |
        docker run -it --name container --privileged -v ${GITHUB_WORKSPACE}:/Package -d ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest /bin/bash

    - name: Setup environment and build
      shell: bash
      run: |
          cat <<'EOF' > ${GITHUB_WORKSPACE}/script_container.sh
          set -e
          /mount.sh

          if [ "${{ inputs.build_type }}" = "release" ]; then
            source /cvmfs/sw.hsf.org/key4hep/setup.sh
          else
            source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
          fi

          cd /Package
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../install -G Ninja
          ninja install
          ctest -j $(nproc) --output-on-failure


          EOF

          cat ${GITHUB_WORKSPACE}/script_container.sh

          docker exec container /bin/bash ${GITHUB_WORKSPACE}/script_container.sh
