name: Auto commit

on:
  push:
    branches:
      - master
      - main

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: |
          pip install pre-commit
          pre-commit run --all-files
          if [ -f .clang-format ]; then
            apt install clang-format
            clang-format -i 
          fi
          if [ -f .pylintrc ]; then
            pip install pylint
            pylint
          fi

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v6
        if: always()