name: Key4hep build
description: Build and test using the Key4hep stack

inputs:
  build_type:
    description: release or nightly or other
    required: true
  image:
    description: alma9, ubuntu22 or ubuntu24
    required: true
  stack:
    description: key4hep or devkey or full path to the setup script
    required: false
    default: devkey

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - uses: actions/cache@v5
      with:
        path: ~/.cache/ccache
        key: ${{ inputs.build_type }}-${{ inputs.image }}-${{ env.NOW }}
        restore-keys: |
          ${{ inputs.build_type }}-${{ inputs.image }}

    - name: Start container
      shell: bash
      run: |
        name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
        if [ "${{ inputs.image }}" = "alma9" ]; then
          docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/${name} -v ~/.cache/ccache:/root/.cache/ccache -d ghcr.io/key4hep/key4hep-images/alma9-cvmfs tail -f /dev/null
        elif [ "${{ inputs.image }}" = "ubuntu22" ]; then
          docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/${name} -v ~/.cache/ccache:/root/.cache/ccache -d ghcr.io/key4hep/key4hep-images/ubuntu22-cvmfs tail -f /dev/null
        elif [ "${{ inputs.image }}" = "ubuntu24" ]; then
          docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/${name} -v ~/.cache/ccache:/root/.cache/ccache -d ghcr.io/key4hep/key4hep-images/ubuntu24-cvmfs tail -f /dev/null
        else
          echo "Unknown image"
          exit 1
        fi

    - name: Setup environment and build
      shell: bash
      run: |
          name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          cat <<'EOF' > ${GITHUB_WORKSPACE}/script_container.sh
          set -e

          export CCACHE_DIR=/root/.cache/ccache
          export CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime
          ccache --set-config=max_size=500M
          ccache -z

          name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')

          if [ -x "$(command -v mold)" ]; then
            rm /usr/bin/ld
            ln -s /usr/bin/mold /usr/bin/ld
            echo "Using the mold linker"
          fi

          if [[ "${{ inputs.stack }}" =~ cvmfs ]]; then
            source ${{ inputs.stack }}
          elif [ "${{ inputs.build_type }}" = "release" ]; then
            source /cvmfs/sw.hsf.org/key4hep/setup.sh
            # if [ "${{ inputs.stack }}" = "key4hep" ]; then 
            #   source /cvmfs/sw.hsf.org/key4hep/setup.sh
            # elif [ "${{ inputs.stack }}" = "devkey" ]; then
            #   source /cvmfs/sft.cern.ch/lcg/views/devkey/latest/x86_64-el9-gcc14-opt/setup.sh
            # else
            #   echo "Unknown stack ${{ inputs.stack }}"
            #   exit 1
            # fi
          elif [ "${{ inputs.build_type }}" = "nightly" ]; then
            if [ "${{ inputs.image }}" = "ubuntu24" ]; then
              source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
            else
              source /cvmfs/sft-nightlies.cern.ch/lcg/views/devkey-head/latest/x86_64-el9-gcc14-opt/setup.sh
            fi
          else
            echo "Unknown build type"
            exit 1
          fi

          if [ "$KEY4HEP_STACK" == *"hsf.org"* ]; then
            if command -v mold &>/dev/null; then
              mimalloc=$(echo $(dirname $(dirname $(dirname $(dirname $(which mold)))))/mimalloc/*/lib*/libmimalloc.so)
            fi
          else
            mimalloc_found=""
            IFS=: read -ra dirs <<< "$LD_LIBRARY_PATH"
            for dir in "${dirs[@]}"; do
              candidate="$dir/libmimalloc.so"
              if [ -f "$candidate" ]; then
                mimalloc_found="$candidate"
                break
              fi
            done
            mimalloc="$mimalloc_found"
          fi
          if [ -f "$mimalloc" ]; then
            export LD_PRELOAD=$mimalloc
            echo "Using mimalloc: $mimalloc"
          else
            echo "mimalloc not found, using default allocator"
          fi

          cd /${name}

          # There is no k4_local_repo in the LCG stacks
          if [ -x "$(command -v k4_local_repo)" ]; then
            k4_local_repo
          fi
          mkdir -p build
          cd build

          if [ -f /${name}/.github/workflows/.key4hep-build-env ]; then
            echo "Sourcing .keyhep-build-env"
            echo "----------------------------------"
            cat /${name}/.github/workflows/.key4hep-build-env
            echo "----------------------------------"
            source /${name}/.github/workflows/.key4hep-build-env
          fi

          set -x
          cmake .. \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_FLAGS="-Werror -Wno-error=cpp -Wno-error=deprecated-declarations" \
            -G Ninja \
            ${K4_CMAKE_EXTRA_ARGS}
          set +x

          time ninja -k0 install
          ccache -s

          # For LCG stacks there is nothing pointing to the new environment
          # so we have to make sure that the new files are picked
          if [ "${{ inputs.stack }}" = "devkey" ]; then
            export PATH=/${name}/install/bin:$PATH
            export LD_LIBRARY_PATH=/${name}/install/lib:${name}/install/lib64:$LD_LIBRARY_PATH
            export ROOT_INCLUDE_PATH=/${name}/install/include:$ROOT_INCLUDE_PATH
            export CPATH=/${name}/install/include:$CPATH
            export PYTHONPATH=/${name}/install/lib/python*/site-packages:/${name}/install/python:$PYTHONPATH
          fi

          ctest -j $(nproc) --output-on-failure


          EOF

          chmod +x ${GITHUB_WORKSPACE}/script_container.sh

          # cat ${GITHUB_WORKSPACE}/script_container.sh

          docker exec container /bin/bash -c "/mount.sh && /${name}/script_container.sh"

    - name: Upload EDM4hep file
      if: github.repository == 'key4hep/EDM4hep'
      uses: actions/upload-artifact@v6
      with:
        name: EDM4hep example files (TTree and RNTuple)
        path: |
          ${{ github.workspace }}/build/test/edm4hep_example.root
          ${{ github.workspace }}/build/test/edm4hep_example_rntuple.root
        retention-days: 7
        overwrite: true

    - name: Upload CLDConfig file
      if: github.repository == 'key4hep/CLDConfig'
      uses: actions/upload-artifact@v6
      with:
        name: AIDA ROOT File
        path: |
          ${{ github.workspace }}/CLDConfig/rec_test_edm4hep_aida.root
        retention-days: 7
        overwrite: true

    - name: Upload FCC-config file
      if: github.repository == 'HEP-FCC/FCC-config'
      uses: actions/upload-artifact@v6
      with:
        name: ALLEGRO and IDEA sim-digi-reco files
        path: |
          ${{ github.workspace }}/build/ALLEGRO_sim_digi_reco.root
          ${{ github.workspace }}/build/IDEA_sim_digi_reco.root
        retention-days: 7
        overwrite: true

