name: Key4hep build
description: Build and test using the Key4hep stack

inputs:
  build_type:
    description: release or nightly
    required: true
  image:
    description: alma9, ubuntu22 or centos7
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.cache/ccache
        key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Start container
      shell: bash
      run: |
        if [ "${{ inputs.image }}" = "alma9" ]; then
          docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/Package -v ~/.cache/ccache:/root/.config/ccache -d ghcr.io/key4hep/key4hep-images/alma9-cvmfs tail -f /dev/null
        elif [ "${{ inputs.image }}" = "ubuntu22" ]; then
          docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/Package -v ~/.cache/ccache:/root/.config/ccache -d ghcr.io/key4hep/key4hep-images/ubuntu22-cvmfs tail -f /dev/null
        elif [ "${{ inputs.image }}" = "centos7" ]; then
          docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/Package -v ~/.cache/ccache:/root/.config/ccache -d ghcr.io/key4hep/key4hep-images/centos7-cvmfs tail -f /dev/null
        else
          echo "Unknown image"
          exit 1
        fi

    - name: Setup environment and build
      shell: bash
      run: |
          cat <<'EOF' > ${GITHUB_WORKSPACE}/script_container.sh
          set -e
          /mount.sh

          if [ "${{ inputs.build_type }}" = "release" ]; then
            source /cvmfs/sw.hsf.org/key4hep/setup.sh
          elif [ "${{ inputs.build_type }}" = "nightly" ]; then
            source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
          else
            echo "Unknown build type"
            exit 1
          fi

          cd /Package
          mkdir build
          cd build

          name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          export PATH=$(echo $PATH | tr ':' '\n' | grep -v "/$name/" | tr '\n' ':')
          export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH | tr ':' '\n' | grep -v "/$name/" | tr '\n' ':')
          export ROOT_INCLUDE_PATH=$(echo $ROOT_INCLUDE_PATH | tr ':' '\n' | grep -v "/$name/" | tr '\n' ':')
          export CPATH=$(echo $CPATH | tr ':' '\n' | grep -v "/$name/" | tr '\n' ':')
          export PYTHONPATH=$(echo $PYTHONPATH | tr ':' '\n' | grep -v "/$name/" | tr '\n' ':')

          if [ "${{ inputs.build_type }}" = "nightly" ]; then
            cmake .. -DCMAKE_CXX_STANDARD=20 -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_LAUNCHER=ccache -G Ninja
          else
            cmake .. -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_LAUNCHER=ccache -G Ninja
          fi
          ninja install
          ctest -j $(nproc) --output-on-failure


          EOF

          cat ${GITHUB_WORKSPACE}/script_container.sh

          docker exec container /bin/bash /Package/script_container.sh
