name: 'Build downstream'
description: 'Build dependent packages and branches'
runs:
  using: "composite"
  steps:
    - name: Start container
      shell: bash
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package/main -v /cvmfs:/cvmfs:shared -d ghcr.io/key4hep/key4hep-images/centos7:latest /bin/bash

    - shell: bash
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package;\

        # Set up cvmfs to get git, python, etc and then
        # set up spack and key4hep-spack to match the commits
        # used for building so that none of the packages of the build are rebuilt
        source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh;\
        rel=$(find /cvmfs/sw-nightlies.hsf.org/key4hep/releases/ -maxdepth 3 -type f -wholename "*/.scratch" | sort -r | head -1);\
        rel=$(dirname $rel);\
        echo "rel is $rel";\

        git clone https://github.com/spack/spack --single-branch;\
        cd spack;\
        git checkout $(cat $rel/.spack-commit);\
        cd ..;\
        source spack/share/spack/setup-env.sh;\

        git clone https://github.com/key4hep/key4hep-spack --single-branch;\
        cd key4hep-spack;\
        git checkout $(cat $rel/.key4hep-spack-commit);\
        spack env activate environments/key4hep-nightly
        cd ..;\

        name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]');\
        echo $name;\

        git clone https://github.com/key4hep/key4hep-dev-utils --depth 1;\
        branch_packages=$(python3 /Package/key4hep-dev-utils/scripts/parse.py "${{ github.event.pull_request.body }}");\
        echo "branch_packages = $branch_packages";\
        spack repo add key4hep-spack;\
        spack config add "upstreams:nightly:install_tree: $rel";\
        python3 /Package/key4hep-dev-utils/scripts/fetch_and_checkout.py $name "$branch_packages";\
        cd main;\
        default_branch=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5-);\
        python3 /Package/key4hep-dev-utils/scripts/add_versions_to_spec.py $name key4hep-spack/environments/key4hep-nightly/spack.yaml $rel $default_branch;\
        spack develop --no-clone --path $PWD $name@$default_branch;\
        spack concretize -f;\
        spack install;\
        '
