name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        build_type: ["release", "nightly"]
        image: ["alma9"]
        include:
          - build_type: nightly
            image: ubuntu24
          - build_type: nightly
            image: ubuntu26
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6
      - uses: ./key4hep-build
        with:
          build_type: ${{ matrix.build_type }}
          image: ${{ matrix.image }}
